name: symbiontDivider
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::trim-galore=0.6.6
  - bioconda::bowtie2=2.4.2
  - bioconda::samtools=1.11
  - bioconda::abyss=2.3.0
  - bioconda::busco=4.1.2